
`define fsm_enumDefinition_binary_sequential_type [3:0]
`define fsm_enumDefinition_binary_sequential_fsm_BOOT 4'b0000
`define fsm_enumDefinition_binary_sequential_fsm_IDLE 4'b0001
`define fsm_enumDefinition_binary_sequential_fsm_WAIT 4'b0010
`define fsm_enumDefinition_binary_sequential_fsm_Judge_Before_Fifo 4'b0011
`define fsm_enumDefinition_binary_sequential_fsm_Judge_After_Fifo 4'b0100
`define fsm_enumDefinition_binary_sequential_fsm_READ_S_DATA_1 4'b0101
`define fsm_enumDefinition_binary_sequential_fsm_WAIT_S_DATA_1 4'b0110
`define fsm_enumDefinition_binary_sequential_fsm_Direct_Data 4'b0111
`define fsm_enumDefinition_binary_sequential_fsm_Judge_Col 4'b1000
`define fsm_enumDefinition_binary_sequential_fsm_Judge_Row 4'b1001

